baseURL = 'https://example.org/'
locale = 'en-us'
title = 'Van Horn Lab'

[module]
  [[module.imports]]
    path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify"
  [[module.imports]]
    path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-reveal"
  [[module.imports]]
    path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-bootstrap/v5"
  [[module.imports]]
    path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-core"
  [[module.imports]]
    path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-seo"

[params]
  description = "A modern academic lab site"

[menus]
  [[menus.main]]
    name = "Home"
    url = "/"
    weight = 10

  [[menus.main]]
    name = "Research"
    url = "/research/"
    weight = 20

  [[menus.main]]
    name = "People"
    url = "/people/"
    weight = 30

  [[menus.main]]
    name = "Publications"
    url = "/publications/"
    weight = 40

  [[menus.main]]
    name = "Lab Information"
    url = "/lab-information/"
    weight = 50

  [[menus.main]]
    name = "Contact"
    url = "/contact/"
    weight = 60

[security]
  [security.funcs]
    getenv = ['^HUGO_', '^CI$', '^WC_']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
